// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OvrApp.API.Data;

namespace OvrApp.API.Migrations
{
    [DbContext(typeof(OvrAppContext))]
    [Migration("20181017152131_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OvrApp.API.Models.Eligibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DLNumber");

                    b.Property<DateTime?>("Dob");

                    b.Property<string>("Firstname");

                    b.Property<string>("IsCitizen");

                    b.Property<string>("IsFelon");

                    b.Property<string>("IsMentalIncomp");

                    b.Property<DateTime?>("IssueDate");

                    b.Property<string>("LastName");

                    b.Property<string>("LastSSN");

                    b.Property<string>("MiddleName");

                    b.Property<bool>("NewRegistration");

                    b.Property<bool>("RecordUpdate");

                    b.Property<bool>("RequesttoReplace");

                    b.Property<string>("Suffix");

                    b.HasKey("Id");

                    b.ToTable("Eligibilitys");
                });
#pragma warning restore 612, 618
        }
    }
}
