// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OvrApp.API.Data;

namespace OvrApp.API.Migrations
{
    [DbContext(typeof(OvrAppContext))]
    [Migration("20181119075324_update-ovrApplication")]
    partial class updateovrApplication
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OvrApp.API.Models.Eligibility", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DLNumber");

                    b.Property<DateTime?>("Dob");

                    b.Property<string>("Firstname");

                    b.Property<string>("IsCitizen");

                    b.Property<string>("IsFelon");

                    b.Property<string>("IsMentalIncomp");

                    b.Property<DateTime?>("IssueDate");

                    b.Property<string>("LastName");

                    b.Property<string>("LastSSN");

                    b.Property<string>("MiddleName");

                    b.Property<bool>("NewRegistration");

                    b.Property<bool>("RecordUpdate");

                    b.Property<bool>("RequesttoReplace");

                    b.Property<string>("Suffix");

                    b.HasKey("Id");

                    b.ToTable("Eligibilitys");
                });

            modelBuilder.Entity("OvrApp.API.Models.OvrApplication", b =>
                {
                    b.Property<long>("OvrApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApplicationType");

                    b.Property<string>("BrowserVersion")
                        .HasMaxLength(25);

                    b.Property<string>("ClientAttribute");

                    b.Property<string>("ClientId")
                        .HasMaxLength(40);

                    b.Property<string>("CountyOfResidence")
                        .HasMaxLength(3);

                    b.Property<DateTime?>("CreatedTs");

                    b.Property<DateTime?>("DateOfBirth");

                    b.Property<string>("DaytimeAreaCode")
                        .HasMaxLength(3);

                    b.Property<string>("DaytimePhone")
                        .HasMaxLength(7);

                    b.Property<string>("DaytimePhoneExtension")
                        .HasMaxLength(5);

                    b.Property<DateTime?>("DlIssueDate");

                    b.Property<string>("EmailConfirmation")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .HasMaxLength(30);

                    b.Property<string>("FlDlNum")
                        .HasMaxLength(13);

                    b.Property<string>("FormerAddrCity")
                        .HasMaxLength(40);

                    b.Property<string>("FormerAddrCountry")
                        .HasMaxLength(25);

                    b.Property<string>("FormerAddrLine1")
                        .HasMaxLength(40);

                    b.Property<string>("FormerAddrLine2")
                        .HasMaxLength(40);

                    b.Property<string>("FormerAddrState")
                        .HasMaxLength(2);

                    b.Property<string>("FormerAddrZip")
                        .HasMaxLength(15);

                    b.Property<string>("FormerFirstName")
                        .HasMaxLength(29);

                    b.Property<string>("FormerLastName")
                        .HasMaxLength(29);

                    b.Property<string>("FormerMiddleName")
                        .HasMaxLength(29);

                    b.Property<string>("FromerAddrLine3")
                        .HasMaxLength(40);

                    b.Property<long?>("FvrsStreetSegmentId");

                    b.Property<string>("Gender")
                        .HasMaxLength(1);

                    b.Property<int?>("HSMVRetries");

                    b.Property<string>("Hashcode");

                    b.Property<DateTime?>("HsmvMatchDatetime");

                    b.Property<long?>("HsmvMatchId");

                    b.Property<DateTime?>("HsmvMatchSignatureDate");

                    b.Property<short?>("HsmvMatchStatus");

                    b.Property<bool?>("IsManualAddress");

                    b.Property<DateTime?>("LastModifiedTs");

                    b.Property<string>("LastName")
                        .HasMaxLength(30);

                    b.Property<string>("MailAddrCity")
                        .HasMaxLength(40);

                    b.Property<string>("MailAddrCountry")
                        .HasMaxLength(25);

                    b.Property<string>("MailAddrLine1")
                        .HasMaxLength(40);

                    b.Property<string>("MailAddrLine2")
                        .HasMaxLength(40);

                    b.Property<string>("MailAddrLine3")
                        .HasMaxLength(40);

                    b.Property<string>("MailAddrState")
                        .HasMaxLength(2);

                    b.Property<string>("MailAddrZip")
                        .HasMaxLength(15);

                    b.Property<bool?>("MailingAddSameAsResi");

                    b.Property<bool>("MentalIncompStatus");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(30);

                    b.Property<bool?>("Military");

                    b.Property<bool?>("MilitaryDependent");

                    b.Property<string>("NameSuffix")
                        .HasMaxLength(5);

                    b.Property<bool?>("NewRegistration");

                    b.Property<bool>("NotAFelon");

                    b.Property<int?>("OVRStatus");

                    b.Property<bool?>("OverseasFlag");

                    b.Property<string>("PartyAffiliation")
                        .HasMaxLength(3);

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(50);

                    b.Property<bool?>("PollWorkerVolunteer");

                    b.Property<string>("PublicEmailAddress")
                        .HasMaxLength(100);

                    b.Property<int>("RaceId");

                    b.Property<bool?>("RecordUpdate");

                    b.Property<string>("ReferralCampaign")
                        .HasMaxLength(25);

                    b.Property<string>("ReferralSourceId")
                        .HasMaxLength(10);

                    b.Property<string>("ReferralSourceType")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("RegDate");

                    b.Property<bool?>("RequestSampleBallotByEmail");

                    b.Property<bool?>("RequesttoReplace");

                    b.Property<string>("ResStreetName")
                        .HasMaxLength(45);

                    b.Property<long?>("ResStreetNumber");

                    b.Property<string>("ResStreetNumberSuffix")
                        .HasMaxLength(4);

                    b.Property<string>("ResStreetPostDirection")
                        .HasMaxLength(2);

                    b.Property<string>("ResStreetPreDirection")
                        .HasMaxLength(2);

                    b.Property<string>("ResStreetType")
                        .HasMaxLength(4);

                    b.Property<string>("ResUnitNumber")
                        .HasMaxLength(20);

                    b.Property<string>("ResUnitType")
                        .HasMaxLength(6);

                    b.Property<string>("ResUspsCityName")
                        .HasMaxLength(40);

                    b.Property<string>("ResZipCode")
                        .HasMaxLength(5);

                    b.Property<string>("ResZipCodePlus4")
                        .HasMaxLength(4);

                    b.Property<string>("SessionId")
                        .HasMaxLength(40);

                    b.Property<string>("SsnLast4")
                        .HasMaxLength(4);

                    b.Property<DateTime?>("SubmittedTs");

                    b.Property<string>("TransferID")
                        .HasMaxLength(40);

                    b.Property<bool>("UsCitizen");

                    b.Property<bool?>("VoterClaimsNoSsnOrDln");

                    b.Property<bool?>("VotingAssistRequired");

                    b.Property<string>("WebBrowser");

                    b.HasKey("OvrApplicationId");

                    b.ToTable("OvrApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
